[profile.default]
src = 'contracts'
out = 'build'
libs = ["node_modules"]
test = 'test'
cache_path  = 'cache_forge'
fs_permissions = [{ access = "read", path = "./"}]
optimizer = true
optimizer_runs = 100

# Exclude test files from coverage reports
no_match_coverage = "(^test/|/mocks/)"

# Lint configuration
[lint]
ignore = ["contracts/mocks/imports.sol"]
exclude_lints = ["mixed-case-function", "mixed-case-variable"]
