name: E2E

env:
  CI: true

on:
  push:
    branches: [main]
    paths:
      - packages/contracts/contracts/**
      - packages/contracts/config/**
      - packages/contracts/e2e/**
      - packages/contracts/cli/**
      - packages/contracts/tasks/**
      - packages/contracts/scripts/**
      - packages/contracts/hardhat.config.ts
  pull_request: {}

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Run e2e tests
        run: |
          git clone https://github.com/edgeandnode/nitro
          pushd nitro
          git submodule update --init --recursive
          ./test-node.bash --init --no-blockscout --detach
          popd
          L1_NETWORK=localnitrol1 L2_NETWORK=localnitrol2 yarn test:e2e
